DROP SCHEMA IF EXISTS DATOS;
CREATE DATABASE DATOS;

USE DATOS;
CREATE TABLE RESERVAS (
ID INT AUTO_INCREMENT PRIMARY KEY,
FECHA TIMESTAMP NULL DEFAULT NULL,
NOMBRE_PACIENTE VARCHAR(250) NULL,
ESTADO VARCHAR(25) NOT NULL DEFAULT 'REGISTRADO'
);

INSERT INTO RESERVAS (fecha, nombre_paciente, estado) VALUES ('2023-11-20 10:00:00', 'Alejandro Ortega', 'Pendiente');
INSERT INTO RESERVAS (fecha, nombre_paciente, estado) VALUES ('2023-11-20 11:00:00', 'Isabel Plaza', 'Confirmada');
INSERT INTO RESERVAS (fecha, nombre_paciente, estado) VALUES ('2023-11-20 11:00:00', 'Aaron Rodriguez', 'Cancelada');


SELECT *  FROM RESERVAS;